@extends('layouts.customer')

@section('title', 'Profil & Pengaturan - Barber Woi')

@section('content')
<div class="mb-7"><p class="mb-1 text-[11px] font-bold uppercase tracking-[0.18em] text-gold">Akun Anda</p><h1 class="font-heading text-2xl font-bold tracking-tight text-charcoal sm:text-3xl">Profil & Pengaturan</h1><p class="mt-2 text-sm text-muted">Kelola informasi akun dan keamanan Anda.</p></div>
<div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
    <aside class="rounded-xl border border-gray-200 bg-white p-5 text-center lg:text-left"><span class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-charcoal font-heading text-2xl font-bold text-gold lg:mx-0">{{ strtoupper(substr($user->name, 0, 1)) }}</span><h2 class="mt-4 font-heading text-lg font-bold text-charcoal">{{ $user->name }}</h2><p class="mt-1 break-all text-sm text-muted">{{ $user->email }}</p><div class="mt-5 border-t border-gray-100 pt-4 text-left"><a href="{{ route('customer.booking.index') }}" class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-muted hover:bg-cream hover:text-charcoal"><span class="material-symbols-outlined">calendar_month</span>Booking Saya</a><a href="{{ route('customer.reviews.index') }}" class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-muted hover:bg-cream hover:text-charcoal"><span class="material-symbols-outlined">rate_review</span>Ulasan Saya</a><a href="{{ route('notifications.index') }}" class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-muted hover:bg-cream hover:text-charcoal"><span class="material-symbols-outlined">notifications</span>Notifikasi</a></div><form method="POST" action="{{ route('logout') }}" class="mt-4 border-t border-gray-100 pt-4">@csrf<button class="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-branddanger hover:bg-red-50"><span class="material-symbols-outlined">logout</span>Keluar</button></form></aside>
    <div class="space-y-6 lg:col-span-2">
        <section class="rounded-xl border border-gray-200 bg-white p-5 sm:p-6"><div class="mb-5 border-b border-gray-100 pb-4"><h2 class="font-heading text-lg font-bold text-charcoal">Informasi Profil</h2><p class="mt-1 text-sm text-muted">Perbarui nama dan alamat email akun Anda.</p></div><form method="post" action="{{ route('profile.update') }}" class="space-y-4">@csrf @method('patch')<div><label for="name" class="text-sm font-semibold text-charcoal">Nama</label><input id="name" name="name" type="text" value="{{ old('name', $user->name) }}" required autofocus class="mt-1.5 block w-full rounded-lg border-gray-200 bg-cream px-3 py-2.5 text-sm focus:border-gold focus:ring-gold"><x-input-error :messages="$errors->get('name')" class="mt-2" /></div><div><label for="email" class="text-sm font-semibold text-charcoal">Email</label><input id="email" name="email" type="email" value="{{ old('email', $user->email) }}" required class="mt-1.5 block w-full rounded-lg border-gray-200 bg-cream px-3 py-2.5 text-sm focus:border-gold focus:ring-gold"><x-input-error :messages="$errors->get('email')" class="mt-2" /></div><div class="flex items-center gap-3 pt-1"><button class="rounded-lg bg-charcoal px-4 py-2.5 text-sm font-bold text-white hover:bg-charcoal/90">Simpan Perubahan</button>@if(session('status') === 'profile-updated')<span class="text-sm font-semibold text-brandsuccess">Tersimpan</span>@endif</div></form></section>
        <section class="rounded-xl border border-gray-200 bg-white p-5 sm:p-6"><div class="mb-5 border-b border-gray-100 pb-4"><h2 class="font-heading text-lg font-bold text-charcoal">Keamanan Akun</h2><p class="mt-1 text-sm text-muted">Gunakan password yang kuat untuk menjaga keamanan akun.</p></div><form method="post" action="{{ route('password.update') }}" class="space-y-4">@csrf @method('put')<div><label class="text-sm font-semibold text-charcoal" for="update_password_current_password">Password Saat Ini</label><input id="update_password_current_password" name="current_password" type="password" autocomplete="current-password" class="mt-1.5 block w-full rounded-lg border-gray-200 bg-cream px-3 py-2.5 text-sm focus:border-gold focus:ring-gold"><x-input-error :messages="$errors->updatePassword->get('current_password')" class="mt-2" /></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label class="text-sm font-semibold text-charcoal" for="update_password_password">Password Baru</label><input id="update_password_password" name="password" type="password" autocomplete="new-password" class="mt-1.5 block w-full rounded-lg border-gray-200 bg-cream px-3 py-2.5 text-sm focus:border-gold focus:ring-gold"><x-input-error :messages="$errors->updatePassword->get('password')" class="mt-2" /></div><div><label class="text-sm font-semibold text-charcoal" for="update_password_password_confirmation">Konfirmasi Password</label><input id="update_password_password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" class="mt-1.5 block w-full rounded-lg border-gray-200 bg-cream px-3 py-2.5 text-sm focus:border-gold focus:ring-gold"><x-input-error :messages="$errors->updatePassword->get('password_confirmation')" class="mt-2" /></div></div><div class="flex items-center gap-3 pt-1"><button class="rounded-lg border border-charcoal px-4 py-2.5 text-sm font-bold text-charcoal hover:bg-cream">Ubah Password</button>@if(session('status') === 'password-updated')<span class="text-sm font-semibold text-brandsuccess">Password diperbarui</span>@endif</div></form></section>
    </div>
</div>
@endsection
